class Autogenerated {
  Data? data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<Cities>? cities;

  Data({this.cities});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['cities'] != null) {
      cities = <Cities>[];
      json['cities'].forEach((v) {
        cities!.add(new Cities.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.cities != null) {
      data['cities'] = this.cities!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Cities {
  int? id;
  int? regionId;
  String? slug;
  String? name;
  Null? code;
  String? latitude;
  String? longitude;
  String? location;
  int? order;
  bool? active;
  Null? status;

  Cities({
    this.id,
    this.regionId,
    this.slug,
    this.name,
    this.code,
    this.latitude,
    this.longitude,
    this.location,
    this.order,
    this.active,
    this.status
  });

  Cities.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    regionId = json['region_id'];
    slug = json['slug'];
    name = json['name'];
    code = json['code'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    location = json['location'];
    order = json['order'];
    active = json['active'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['region_id'] = this.regionId;
    data['slug'] = this.slug;
    data['name'] = this.name;
    data['code'] = this.code;
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['location'] = this.location;
    data['order'] = this.order;
    data['active'] = this.active;
    data['status'] = this.status;
    return data;
  }
}
